// Tauri 构建脚本（BUG-5 严格修复：应用命令 ACL 门禁）
//
// 默认 tauri_build::build() 不声明 AppManifest.commands——app 无权限清单
// （has_app_acl=false），自定义命令一律放行（capability 门禁形同虚设）。
// 声明全部命令后 tauri-build 在 permissions/autogenerated/ 生成
// allow-<command> 权限（下划线转连字符），app ACL 启用：
// 前端只能调用 capability 白名单内的命令，未引用命令被拒。
fn main() {
    let attributes =
        tauri_build::Attributes::new().app_manifest(tauri_build::AppManifest::new().commands(&[
            "get_cli_args",
            "read_file",
            "write_file",
            "list_dir",
            "create_file",
            "create_dir",
            "rename_path",
            "duplicate_path",
            "delete_to_trash",
            "watch_dir",
            "save_draft",
            "list_drafts",
            "recover_draft",
        ]));
    // 构建脚本入口：失败即打印错误并退出（与 lib.rs run() 同风格，不 panic）
    if let Err(e) = tauri_build::try_build(attributes) {
        eprintln!("Tauri 构建失败: {e}");
        std::process::exit(1);
    }
}
