// Tauri 构建脚本（BUG-5 严格修复：应用命令 ACL 门禁）
//
// 默认 tauri_build::build() 不声明 AppManifest.commands——app 无权限清单
// （has_app_acl=false），自定义命令一律放行（capability 门禁形同虚设）。
// 声明全部命令后 tauri-build 在 permissions/autogenerated/ 生成
// allow-<command> 权限（下划线转连字符），app ACL 启用：
// 前端只能调用 capability 白名单内的命令，未引用命令被拒。
//
// Windows manifest（D2 追加）：tauri-winres 只把 Common-Controls v6 manifest
// 嵌入主程序二进制（embed-resource 内部用 rustc-link-arg-bins，仅主程序生效），
// 测试 harness 二进制缺 manifest——测试链接 wry 后 TaskDialogIndirect 无入口
// （comctl32 v5 不导出该符号），进程启动即 0xc0000139（tauri#13419/#14580）。
// 此处改用 rustc-link-arg（作用于本包全部目标，含测试）手动嵌入与 tauri-build
// 默认同款的 manifest，主程序行为不变，测试二进制同样可启动。
fn main() {
    let attributes = tauri_build::Attributes::new()
        .app_manifest(tauri_build::AppManifest::new().commands(&[
            "get_cli_args",
            "read_file",
            "write_file",
            "list_dir",
            "create_file",
            "create_dir",
            "rename_path",
            "duplicate_path",
            "delete_to_trash",
            "watch_dir",
            "unwatch_dir",
            "save_draft",
            "list_drafts",
            "recover_draft",
        ]))
        // 关闭 tauri-build 默认 manifest：改由下方 rustc-link-arg 统一嵌入，
        // 否则主程序出现两份 manifest 资源（winres 一份 + 链接器一份）冲突
        .windows_attributes(tauri_build::WindowsAttributes::new_without_app_manifest());
    #[cfg(windows)]
    embed_windows_manifest();
    // 构建脚本入口：失败即打印错误并退出（与 lib.rs run() 同风格，不 panic）
    if let Err(e) = tauri_build::try_build(attributes) {
        eprintln!("Tauri 构建失败: {e}");
        std::process::exit(1);
    }
}

/// 嵌入 Common-Controls v6 manifest（内容与 tauri-build 默认 windows-app-manifest.xml 完全一致）
///
/// 仅 Windows 生效（构建脚本按宿主平台编译）。manifest 先写入 OUT_DIR 再以绝对路径
/// 传给链接器，规避链接器工作目录与包根目录不一致的路径解析问题。
#[cfg(windows)]
fn embed_windows_manifest() {
    let manifest = r#"<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <dependency>
    <dependentAssembly>
      <assemblyIdentity
        type="win32"
        name="Microsoft.Windows.Common-Controls"
        version="6.0.0.0"
        processorArchitecture="*"
        publicKeyToken="6595b64144ccf1df"
        language="*"
      />
    </dependentAssembly>
  </dependency>
</assembly>"#;
    let out_dir = match std::env::var("OUT_DIR") {
        Ok(dir) => dir,
        Err(e) => {
            eprintln!("读取 OUT_DIR 失败: {e}");
            std::process::exit(1);
        }
    };
    let manifest_path = std::path::Path::new(&out_dir).join("windows-app-manifest.xml");
    if let Err(e) = std::fs::write(&manifest_path, manifest) {
        eprintln!("写入 Windows manifest 失败: {e}");
        std::process::exit(1);
    }
    // rustc-link-arg 而非 tauri-winres 的 link-arg-bins：测试 harness 也能获得 manifest
    println!("cargo:rustc-link-arg=/MANIFEST:EMBED");
    println!(
        "cargo:rustc-link-arg=/MANIFESTINPUT:{}",
        manifest_path.display()
    );
}
